version: "3.8"

services:
  simple_todo_app_db:
    image: postgres:15
    container_name: simple_todo_app_db
    restart: always
    environment:
      POSTGRES_USER: simple_todo_api_user
      POSTGRES_PASSWORD: simple_todo_api_password
    ports:
      - "5234:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d

volumes:
  postgres_data:
